name: augenblick
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - iopath
dependencies:
  - python=3.10
  - pip=25.1
  - pytorch=2.3.1
  - pytorch-cuda=11.8
  - torchvision==0.18.1
  - torchaudio
  - cuda-toolkit=11.8
  - ninja
  - iopath
  - fvcore

  - pip:
    - numpy==1.26.1
    - Pillow
    - huggingface_hub
    - einops
    - safetensors
    - networkx==3.1
    - opencv-python~=4.5.5.62
    - open3d
    - matplotlib
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - tqdm~=4.62.2
    - hydra-core
    - omegaconf
    - onnxruntime
    - requests
    - trimesh
    - commentjson~=0.9.0
    - imageio~=2.16.0
    - pybind11~=2.7.1
    - tensorboard