# Stage 3: Fine detail reconstruction (10k-20k iterations)
# Full resolution for capturing fine anatomical details

data:
  type: projects.neuralangelo.data
  root: /blue/arthur.porto-biocosmos/jhennessy7.gatech/scratch/neuralangelo_b200_20250721_144006
  name: transforms.json  # Use converted NeRF-style cameras
  num_images: 138
  num_workers: 4  # Reduced for memory
  preload: false
  use_multi_epoch_loader: true
  # Sphere normalization from original config
  readjust:
    center: [0.6389583298477574, 0.6039861034655917, 0.5979484190111575]
    scale: 0.8946571020905045
  train:
    batch_size: 1
    image_size: [4160, 6240]  # Full resolution (corrected from 2080x3120)
  val:
    batch_size: 1
    image_size: [2080, 3120]
    subset: 1

model:
  type: projects.neuralangelo.model
  background:
    enabled: false  # Disable background since we have masks
    white: true
  object:
    sdf:
      encoding:
        type: hashgrid
        base_resolution: 16
        n_features_per_level: 2
        log2_hashmap_size: 22  # Keep full size
        levels: 18  # Maximum levels
        max_logres: 13  # Higher resolution for fine details
        coarse2fine:
          enabled: true
          init_active_level: 8
          step: 500
      gradient:
        mode: numerical
        taps: 4  # Higher quality gradients
      mlp:
        activ: softplus
        activ_params:
          beta: 100
        hidden_dim: 256
        num_layers: 6
        skip: [4]
        checkpoint: true
        geometric_init: true
        weight_norm: true
    rgb:
      mode: idr
      encoding_view:
        type: spherical
        levels: 4
      mlp:
        activ: relu_
        hidden_dim: 128
        num_layers: 4
        weight_norm: true
  render:
    num_samples:
      coarse: 96  # More samples for quality
      fine: 48
      background: 0  # No background samples
    rand_rays: 2048  # Maximum rays (increased from 1024)
    stratified: true
    mask_background: true

trainer:
  type: projects.neuralangelo.trainer
  amp_config:
    enabled: true
    init_scale: 65536.0
  grad_accum_iter: 2  # Reduced to manage memory at full resolution
  loss_weight:
    render: 1.0
    eikonal: 0.1
    curvature: 0.001  # Higher for smoother surface
  skip_initial_validation: true
  ema_config:
    enabled: true
    beta: 0.9999
    start_iteration: 10100

optim:
  type: AdamW
  params:
    lr: 0.0005  # Low learning rate for fine-tuning
    weight_decay: 0.01
  sched:
    type: two_steps_with_warmup
    warm_up_end: 10100
    two_steps: [15000, 18000]

# Training settings
max_iter: 20000  # Total iterations (continues from 10k)
logging_iter: 100
checkpoint:
  save_iter: 2000
  save_latest_iter: 500

# Validation settings
validation_iter: 2000
image_save_iter: 9999999
